# Generated by Django 5.1 on 2024-08-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_sim', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('paysDeResidence', models.CharField(max_length=50)),
                ('revenu', models.CharField(max_length=50)),
                ('clientBiat', models.BooleanField()),
                ('typeDuBien', models.CharField(max_length=50)),
                ('valeurDeVotreProjet', models.CharField(max_length=100)),
                ('montantMaximumDeCredit', models.CharField(max_length=100)),
                ('votreAutofinancement', models.CharField(max_length=100)),
                ('creditSollicite', models.CharField(max_length=100)),
                ('dureeDeRemboursementSouhaitee', models.CharField(max_length=2)),
            ],
        ),
    ]
