# Generated by Django 5.1 on 2024-08-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_simulation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='type_de_bien_consulte',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='creditSollicite',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='montantMaximumDeCredit',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='paysDeResidence',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='valeurDeVotreProjet',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='votreAutofinancement',
            field=models.CharField(max_length=50),
        ),
    ]
