# Generated by Django 5.1 on 2024-08-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_client_type_de_bien_consulte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
