# Generated by Django 5.1 on 2024-08-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_simulation_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='nom',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='client',
            name='numero_de_telephone',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='client',
            name='simulation_de_credit',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='client',
            name='source_du_lead',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='client',
            name='statut_du_contact',
            field=models.TextField(choices=[('Contacté', 'Contacté'), ('RDV programmé', 'RDV programmé'), ('En attente', 'En attente')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='type_de_bien_consulte',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='creditSollicite',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='dureeDeRemboursementSouhaitee',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='mobile',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='montantMaximumDeCredit',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='nom_sim',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='paysDeResidence',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='prenom',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='revenu',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='typeDuBien',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='valeurDeVotreProjet',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='votreAutofinancement',
            field=models.TextField(),
        ),
    ]
