# Generated by Django 5.1 on 2024-08-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_client_id_alter_client_statut_du_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='nom',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='numero_de_telephone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='source_du_lead',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='statut_du_contact',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='type_de_bien_consulte',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='creditSollicite',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='dureeDeRemboursementSouhaitee',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='mobile',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='montantMaximumDeCredit',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='nom_sim',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='paysDeResidence',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='prenom',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='revenu',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='typeDuBien',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='valeurDeVotreProjet',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='votreAutofinancement',
            field=models.CharField(max_length=255),
        ),
    ]
