# Generated by Django 5.1 on 2024-08-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_alter_client_email_alter_client_nom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='agence',
            field=models.CharField(default='biat', max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='estclientbiat',
            field=models.BooleanField(default=False),
        ),
    ]
