# Generated by Django 5.1 on 2024-09-02 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_client_agence_client_estclientbiat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='estclientbiat',
            new_name='est_client_biat',
        ),
    ]
