# Generated by Django 5.1 on 2024-09-02 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_rename_estclientbiat_client_est_client_biat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simulation',
            old_name='clientBiat',
            new_name='client_biat',
        ),
        migrations.RenameField(
            model_name='simulation',
            old_name='creditSollicite',
            new_name='credit_sollicite',
        ),
        migrations.RenameField(
            model_name='simulation',
            old_name='dureeDeRemboursementSouhaitee',
            new_name='duree_de_Remboursement_souhaitee',
        ),
        migrations.RenameField(
            model_name='simulation',
            old_name='montantMaximumDeCredit',
            new_name='montant_maximum_de_credit',
        ),
        migrations.RenameField(
            model_name='simulation',
            old_name='paysDeResidence',
            new_name='pays_De_Residence',
        ),
        migrations.RenameField(
            model_name='simulation',
            old_name='typeDuBien',
            new_name='type_du_bien',
        ),
        migrations.RenameField(
            model_name='simulation',
            old_name='valeurDeVotreProjet',
            new_name='valeur_de_votre_projet',
        ),
        migrations.RenameField(
            model_name='simulation',
            old_name='votreAutofinancement',
            new_name='votre_auto_financement',
        ),
    ]
