# Generated by Django 5.1 on 2024-09-02 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_rename_clientbiat_simulation_client_biat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simulation',
            old_name='pays_De_Residence',
            new_name='pays_de_residence',
        ),
    ]
